# Generated by Django 2.2.12 on 2020-05-29 15:18

from django.db import migrations, models
import django.db.models.fields
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('uni_ids', djongo.models.fields.ArrayField(blank=True, model_container=django.db.models.fields.EmailField)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
