# Generated by Django 2.2.12 on 2020-06-07 14:46

import chat.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgRefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_to', models.IntegerField(blank=True)),
                ('refer_by', djongo.models.fields.ArrayField(blank=True, model_container=chat.models.MsgReferBy)),
            ],
        ),
        migrations.CreateModel(
            name='MsgReferBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_by', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='msg_refers',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=chat.models.MsgRefer),
            preserve_default=False,
        ),
    ]
