# Generated by Django 2.2.12 on 2020-05-17 12:11

from django.db import migrations, models
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cgpa_range', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('core_courses', djongo.models.fields.ArrayField(model_container=user_profile.models.CollegeCourse)),
                ('additional_courses', djongo.models.fields.ArrayField(model_container=user_profile.models.CollegeCourse)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('partner_insti', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PoR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('positions', djongo.models.fields.ArrayField(model_container=user_profile.models.Position)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrevIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('from_date', models.CharField(max_length=200)),
                ('to_date', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('school', djongo.models.fields.EmbeddedField(model_container=user_profile.models.School, null=True)),
                ('college', djongo.models.fields.EmbeddedField(model_container=user_profile.models.College, null=True)),
                ('projects', djongo.models.fields.ArrayField(model_container=user_profile.models.Project)),
                ('research_papers', djongo.models.fields.ArrayField(model_container=user_profile.models.ResearchPaper)),
                ('patents', djongo.models.fields.ArrayField(model_container=user_profile.models.Patent)),
                ('prev_interns', djongo.models.fields.ArrayField(model_container=user_profile.models.PrevIntern)),
                ('por', djongo.models.fields.ArrayField(model_container=user_profile.models.PoR)),
                ('online_courses', djongo.models.fields.ArrayField(model_container=user_profile.models.OnlineCourse)),
                ('competitions', djongo.models.fields.ArrayField(model_container=user_profile.models.Competition)),
                ('certifications', djongo.models.fields.ArrayField(model_container=user_profile.models.Certification)),
                ('skills', djongo.models.fields.ArrayField(model_container=user_profile.models.Skill)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('project_type', models.CharField(max_length=10)),
                ('associated_info', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('journal', models.CharField(max_length=200)),
                ('num_of_people', models.IntegerField()),
                ('is_main', models.BooleanField()),
                ('name_of_main', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('board', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
