# Generated by Django 2.2.12 on 2020-05-20 20:34

from django.db import migrations
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200520_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=djongo.models.fields.ArrayField(blank=True, default=None, model_container=user_profile.models.Preferences),
        ),
    ]
