# Generated by Django 2.2.12 on 2020-05-18 17:59

from django.db import migrations, models
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('insti_email', models.EmailField(blank=True, max_length=100)),
                ('password_hash', models.CharField(max_length=300)),
                ('profile', djongo.models.fields.EmbeddedField(blank=True, model_container=user_profile.models.Profile, null=True)),
            ],
        ),
    ]
