# Generated by Django 2.2.12 on 2020-05-17 12:12

from django.db import migrations
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200513_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=djongo.models.fields.EmbeddedField(model_container=user_profile.models.Profile, null=True),
        ),
    ]
