# Generated by Django 2.2.12 on 2020-05-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='issuing_auth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='issuing_auth',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
