# Generated by Django 2.2.12 on 2020-08-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
