# Generated by Django 2.2.12 on 2020-05-20 19:13

from django.db import migrations, models
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200520_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_sectors', djongo.models.fields.ArrayField(blank=True, model_container=user_profile.models.Place)),
                ('prefered_interns', djongo.models.fields.ArrayField(blank=True, model_container=user_profile.models.Place)),
                ('prefered_jobs', djongo.models.fields.ArrayField(blank=True, model_container=user_profile.models.Place)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
