# Generated by Django 2.2.12 on 2020-05-20 21:39

from django.db import migrations, models
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.AddField(
            model_name='college',
            name='type_of_degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='colleges',
            field=djongo.models.fields.ArrayField(blank=True, default=None, model_container=user_profile.models.College),
            preserve_default=False,
        ),
    ]
