# Generated by Django 2.2.12 on 2020-05-21 17:46

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20200520_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_path),
        ),
    ]
