# Generated by Django 2.2.12 on 2020-07-27 19:02

from django.db import migrations, models
import djongo.models.fields
import features.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_pic', models.ImageField(blank=True, null=True, upload_to=features.models.upload_path_person)),
                ('category', models.CharField(max_length=2000)),
                ('experience', djongo.models.fields.ArrayField(model_container=features.models.Experience)),
                ('podcast', models.CharField(blank=True, max_length=5000)),
                ('resources', djongo.models.fields.ArrayField(blank=True, model_container=features.models.Resource)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=5000)),
                ('level', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('cover', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
