# Generated by Django 2.2.12 on 2020-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerlist',
            name='person_fb',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='learnerlist',
            name='person_linkedin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='learnerlist',
            name='person_numouno',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
