# Generated by Django 2.2.12 on 2020-06-05 15:02

import chat.models
from django.db import migrations, models
import djongo.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200529_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(blank=True)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('uni_ids', djongo.models.fields.ArrayField(blank=True, model_container=chat.models.Mail)),
            ],
        ),
        migrations.AddField(
            model_name='mesibogroup',
            name='last_seen_msgs',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=user.models.LastSeen),
            preserve_default=False,
        ),
    ]
